#!/bin/csh
# Version 26-September-2008
###############################################################################
#
# Usage:
#
# make first
# make
# make clean
#
###############################################################################
#        PLEASE, CHECK THAT THE FOLLOWING DEFINITIONS ARE PROPERLY SET
###############################################################################
# MACROS
# -----------------------------------------------------------------------------
# C++ compiler
C_COMPILER = g++ -g -O3 -Wall
#
# Path to the FITSIO library
FITSIO_DIR = /usr/local/cfitsio
# Path to the PGPLOT library
PGPLOT_DIR = /usr/local/pgplot
# Path to libg2c.a
#LIBG2C_DIR = /usr/lib/gcc/x86_64-redhat-linux/4.3.0
# Path to libX11.a
X11LIB_DIR = /usr/lib64
#
# For Solaris use this line:
#SOLLIB = -lnsl -lsocket
#
###############################################################################
#             THE FOLLOWING INSTRUCTIONS SHOULD NOT BE MODIFIED
###############################################################################
# more macro definitions
CSOURCE = c123.cpp \
          checkipar.cpp \
          commandtok.cpp \
          cpgplot_d.cpp \
          fmean.cpp \
          indexdef.cpp \
          indexf.cpp \
          indexparam.cpp \
          issdouble.cpp \
          isslong.cpp \
          loaddpar.cpp \
          loadidef.cpp \
          loadipar.cpp \
          measuresp.cpp \
          mideindex.cpp \
          scidata.cpp \
          showindex.cpp \
          snregion.cpp \
          sustrae_p0.cpp \
          sustrae_p1.cpp \
          verbose.cpp \
          xydata.cpp
COBJECT = $(CSOURCE:.cpp=.o)
# default rule to create program 
# Note that "$@" is a special macro (the name of the file to be made)
#indexf:  $(COBJECT)
#	$(C_COMPILER) -o $@ $(COBJECT)  \
#	-L$(FITSIO_DIR) -L$(PGPLOT_DIR) \
#	-L$(X11LIB_DIR) -L$(LIBG2C_DIR) \
#	-lcfitsio -lcpgplot -lpgplot  -lX11 $(SOLLIB) -lg2c
indexf:  $(COBJECT)
	$(C_COMPILER) -o $@ $(COBJECT)  \
	-L$(FITSIO_DIR) -L$(PGPLOT_DIR) \
	-L$(X11LIB_DIR) \
	-lcfitsio -lcpgplot -lpgplot  -lX11 $(SOLLIB) -lgfortran
# create required include files
first:
	\rm -f installdir.h
	echo "#ifndef INSTALLDIR_H" > installdir.h
	echo "#define INSTALLDIR_H" >> installdir.h
	echo " " >> installdir.h
	echo "const char *installdirPtr=\""`pwd`"/\";" >> installdir.h
	echo " " >> installdir.h
	echo "#endif" >> installdir.h
	touch $(CSOURCE)
# target to clean object modules
clean:
	\rm -f $(COBJECT)
	\rm -f *~
	\rm -f installdir.h
# target to touch source modules
touch:
	touch $(CSOURCE)
# dependencies
# Note that "$?" is a special macro (the name of the changed dependents)
.cpp.o:
	$(C_COMPILER) -I$(FITSIO_DIR) -I$(PGPLOT_DIR) -c $?
